### PR TITLE
feat: added null safety

### PR DESCRIPTION
**Pull request by redDwarf03**

### CODE REVIEW

**Comment by redDwarf03** [comment]
@akassharjun any news about this PR please ?

**Comment by akassharjun** [comment]
Hi @redDwarf03 
Apologies for the late reply, I've been awfully busy with IRL work so I haven't had the chance to maintain the library at all.

PR LGTM, thanks for the contribution! :)

**Comment by redDwarf03** [comment]
no pb. i need your help again. Is it possible to update the project in https://pub.dev/packages/flutter_screen_scaler please

**Comment by akassharjun** [comment]
I've already published it with an update for the example app. @redDwarf03

**Pull request merged**
